
const Component2 = () => {
  return (
    <div id="componente2">
        <h2>Componente 2</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa, ex. Ipsum expedita nisi aliquid deserunt.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tempore quisquam eius ratione magni exercitationem, incidunt suscipit quis pariatur tenetur, labore, sint commodi. Excepturi incidunt autem officiis obcaecati corporis quia, perferendis id nam deleniti eveniet nulla consequuntur voluptatum soluta minus ut. Quibusdam quae molestias ut ipsum rerum sint in illo quidem ex dolor saepe nostrum architecto aut commodi dolore ad temporibus ipsa consectetur ducimus dolorum delectus natus, quasi totam nemo? Nisi consectetur accusantium dicta aspernatur. Veniam ea voluptates unde earum sint nihil eos magnam laudantium corrupti temporibus repellat et cumque beatae dolorum, iure dolorem praesentium cum, fuga ipsam. Aliquid et cupiditate esse voluptatum, error rem unde magnam ad nihil cum adipisci iste accusamus numquam. Eligendi, hic in! Voluptatibus voluptate repudiandae natus fugit fugiat dignissimos enim quis doloremque, itaque consectetur atque hic aspernatur expedita, vel ad inventore maxime fuga corporis excepturi sunt nostrum? Aliquam molestiae, ratione expedita architecto assumenda magnam dolorum sit.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam officiis nemo aut quidem fugit, inventore necessitatibus!</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Inventore, ad nihil? Quasi ducimus recusandae tempora. Id ipsa minus nostrum, facilis quos iure, in accusantium est ea quis sint adipisci. Quis quod ea id accusantium animi optio, sapiente sequi repudiandae pariatur vitae totam eius culpa voluptatem quaerat ad rerum officia aspernatur magnam sint laudantium quas cupiditate blanditiis aperiam. Velit fugiat maxime adipisci excepturi eveniet magnam debitis, recusandae ab ullam repellat impedit saepe sint reiciendis ex quisquam incidunt officia dolore animi delectus tempore architecto assumenda. Illum aliquam odit iure minima facilis expedita ad hic consequuntur, facere quidem repellendus. Itaque consequatur a sunt reiciendis, iure, id, deserunt expedita ducimus corporis sint ea eveniet dolor repellat! Architecto omnis, laborum vel aperiam a consectetur cupiditate eum. Velit perspiciatis itaque tenetur quae quod aspernatur, dicta aliquid saepe veritatis modi nam officiis nulla officia autem, necessitatibus possimus quo labore placeat repellendus! Nihil, incidunt repellat. In quod tenetur dolores iusto dolore iure quibusdam natus aspernatur obcaecati cum animi amet voluptatum, dolorem quisquam, deserunt iste fuga suscipit harum nulla pariatur nemo consequatur enim sed? Debitis dolorum totam ducimus earum cum maxime. Cum perspiciatis sapiente ducimus earum explicabo. Consectetur ipsam fugit nostrum molestias autem ut, voluptatibus commodi magnam voluptatem in iusto laboriosam laborum aperiam vero. Dicta, delectus magni amet nisi sapiente labore quaerat? Explicabo molestiae autem, qui commodi repellendus nam ut alias, labore tenetur aut delectus animi, placeat excepturi vel? Modi quis sequi quae, quasi eius, autem facilis nemo tempora, libero eveniet suscipit voluptatibus harum iste porro repellat et obcaecati.</p>
    </div>
  )
}

export default Component2